### ISSUE TITLE
Hardcode language

### ISSUE THREAD

**Issue by phpbb-es** [privet-fun/phpbb_ailabs#1]
https://github.com/privet-fun/phpbb_ailabs/blob/d8aece5f8cc8d7d73b54e99a2271f3bec345e738/privet/ailabs/styles/prosilver/template/post_ailabs_log.html#L35-L58

You should use language variables for this "labels". ;)

Best regards

**Comment by privet-fun** [comment]
@phpbb-es that log only used for troubleshooting, it is not exposed to user (you have to be admin or moderator to see it), so if someone will need to share logs with me I'd very much prefer it to be in English :)

**Comment by phpbb-es** [comment]
Ahhh, ok sorry!

**Comment by privet-fun** [comment]
@phpbb-es no worries at all!
Did you get a chance to try it out and if so what's your impressions?
