### ISSUE TITLE
Problem with selecting forumswhen creating a new configuration

### ISSUE THREAD

**Issue by HybridMind1337** [privet-fun/phpbb_ailabs#2]
When creating a new configuration, there are issues with selecting forums. The images show that it is possible to choose them, but for me, it's just a list. When i choose one forum i got the error: Please select at least one forum.

Here's a demo:
![image](https://github.com/privet-fun/phpbb_ailabs/assets/12223569/ae46bf13-6bac-4758-b610-a651de2fbde2)

**Comment by privet-fun** [comment]
[HybridMind1337](https://github.com/HybridMind1337) I'm using Chosen jQuery plugin for that control https://github.com/harvesthq/chosen/ (demo https://harvesthq.github.io/chosen/).
Check your [browser dev console](https://balsamiq.com/support/faqs/browserconsole/) to see if there's any errors related to jQuery, also try other browser (eg most recent Chrome).
What's your php/phpBB versions?

**Comment by HybridMind1337** [comment]
my phpbb version is 3.3.8
PHP version is 7.4

in the dev console i dont have any error btw...

**Comment by privet-fun** [comment]
Did you had a chance to try different browser(s)? What's the browser you are using?

At a temp fix you can try to insert config record manually to <prefix>_ailabs_users table, it's pretty straight forward see comments at https://github.com/privet-fun/phpbb_ailabs/blob/main/privet/ailabs/migrations/v1x/release_1_0_0_schema.php

Insert record with desired values in forums_post/forums_reply/forums_mention fields and then use ACP editor to populate the rest once record inserted, it's hacky but should unblock you right away.

**Comment by privet-fun** [comment]
Closed due to inactivity
