### ISSUE TITLE
Problems with posting

### ISSUE THREAD

**Issue by khlebnikov809** [privet-fun/phpbb_ailabs#3]
{
  "start": "2023-10-17 11:23:24",
  "history.pattern": "/<QUOTE\\sauthor=\"Support\"\\spost_id=\"(.*)\"\\stime=\"(.*)\"\\suser_id=\"58\">/",
  "request.messages": [
    {
      "role": "user",
      "content": "Напиши что--нибудь про город Зариснк"
    }
  ],
  "response": {
    "error": {
      "message": "Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact us through our help center at help.openai.com.",
      "type": "access_terminated",
      "param": null,
      "code": "access_terminated"
    }
  },
  "response.codes": [
    429,
    429,
    429
  ],
  "finish": "2023-10-17 11:23:45"
}

Это то что было написано в логе
![image](https://github.com/privet-fun/phpbb_ailabs/assets/63843431/77100a1c-6df3-46b9-9cb4-f947c094dc62)

**Comment by privet-fun** [comment]
You will have to contact OpenAI to sort out access_terminated issue. This usually happen when you share API Keys (prohibited by OpenAI ToS).
