### ISSUE TITLE
Big forum hangs when I try to activate this ext

### ISSUE THREAD

**Issue by superfedya** [privet-fun/phpbb_ailabs#4]
I cannot activate this module on the board with 5 million posts.

Even via php cli.

php-fpm frezes.

Any idea about how to fix it?

**Comment by privet-fun** [comment]
A couple of fields were added to the posts table during the installation of the extension. It appears that MySQL, adhering to an old-school approach, cannot perform this operation without locking the entire table. A proposed fix can be found here: https://stackoverflow.com/questions/35293625/mysql-alter-table-hangs
