### ISSUE TITLE
Simple Mention change BBCode Label  

### ISSUE THREAD

**Issue by cmwang2021** [privet-fun/phpbb_ailabs#5]
The latest version of @mentsion uses [SMENTION u=user_id]user_name[/SMENSTION]. Some modifications may be needed in privet/ailabs/event/listener.php, such as:

// Remove all mentioned AI user names from request
foreach ($ailabs_users as $user) {
    $count = 0;
    $updated = preg_replace('/\[smention\s+u=\d+'\]\S+?\[\/smention\]/', '', $request, -1, $count);
    if ($count > 0) {
        $request = $updated;
    }
}

// Replace smention tags
$request = preg_replace(array('/\[smention\s+u=\d+\]/', '/\[\/smention\]/'), array('', ''), $request);

**Comment by wads24** [comment]
I tried this fix and it did not seem to work...  I think it is not parsing the smention bbcode?

**Comment by privet-fun** [comment]
@cmwang2021 @wads24 I'll need to look at the latest version of the @mention to see what's going on. It should be a simple fix. Probably closer to next weekend.

**Comment by hibobmaster** [comment]
@wads24 

Try to disable phpbb_ailabs extension and re-enable it.

**Comment by privet-fun** [comment]
@wads24 @cmwang2021 please try latest v 1.0.8, I've added support for Simple mention v 2.x
