### ISSUE TITLE
No more responses but initially worked fine

### ISSUE THREAD

**Issue by Loggableim** [privet-fun/phpbb_ailabs#7]
Hi, I had the script working fine and it stopped working yesterday. I didnt change anything. When checking the log it says the following: 

Status
exec
Attempts
0
Mode
reply
Request time
29.2.2024, 21:21:03
Request

{
  "start": "2024-02-29 21:21:04"
}

the response remains empty. 

What could cause this issue? 

thanks for the help!

**Comment by privet-fun** [comment]
@Loggableim Please try the latest version 1.0.8. There was a case where the conversation log was too big to fit into the log field, causing the issue you described above. I have extended the log field size to deal with that. Make sure to disable version 1.0.7 before installing 1.0.8, and then enable it again.
