### ISSUE TITLE
Please select at least one forum

### ISSUE THREAD

**Issue by saper82** [privet-fun/phpbb_ailabs#8]
I try to add bot

I select ALL forums

![Zrzut ekranu 2024-03-22 152935](https://github.com/privet-fun/phpbb_ailabs/assets/34172371/45795757-6b68-4c12-b497-47fa62e7e98d)

but this is not working

![Zrzut ekranu 2024-03-22 152906](https://github.com/privet-fun/phpbb_ailabs/assets/34172371/713f6f25-66c1-48ba-9b86-87301d83914b)

My version phpBB3 3.3.10
AI Labs 1.0.8
PHP: 8.2.16

**Comment by privet-fun** [comment]
@saper82 it does not look like forum was selected, here's how it should look https://github.com/privet-fun/phpbb_ailabs/raw/main/privet/ailabs/docs/midjourney_setup.png
I wonder if dropdown plugin failing in your browser, any chance you can look at console logs? 
What OS/browser are you using? Can you try another browser?

**Comment by saper82** [comment]
I have Windows 11 in the Polish language version.
I tried in Opera, Chrome, Edge and FieFox browsers. The forum selection menu looks the same everywhere. Different than in your graphics.
Tomorrow I will try to test AI Labs on a clean installation of the forum.

https://github.com/privet-fun/phpbb_ailabs/assets/34172371/dd1a0844-7447-4fe1-9893-a2d9b603d41f

**Comment by privet-fun** [comment]
@saper82  [Chosen](https://harvesthq.github.io/chosen/) jQuery plugin is used for multi-selection options. For some reason it is not working on your site.
![image](https://github.com/privet-fun/phpbb_ailabs/assets/134329033/c61a944f-0bbf-4573-8115-cbffbb61d7e5)
