### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by iant62** [privet-fun/phpbb_ailabs#9]
Hi,
I have installed your ailabs per your documenation, but when I click to test the URL that it gives me in the configuration:
![image](https://github.com/user-attachments/assets/0f83d564-1540-42e5-b4ee-833943e178c7)

https://avguru.net/ailabs/chatgpt?job_id=0&sid=baa855cdd437cadbe5c84972374047ba

I get a 404 error. All the other extentions I have work just fine.

Any help would be appreciated..

Thanks
Ian
![AILABS Error](https://github.com/user-attachments/assets/92f76750-734d-4ce0-9856-74bd9a911627)

**Comment by iant62** [comment]
![image](https://github.com/user-attachments/assets/0911aea3-2f27-4292-be21-571bb3aa8246)
 This is what I get when I try to use the functionality

**Comment by iant62** [comment]
Issue resolved by modifying acp_controller.php to reflect correct path

**Comment by goztow** [comment]
What line did you change? I have the same issue.

**Comment by iant62** [comment]
Line 45, changed '/ailabs/chatgpt', to '/app.php/ailabs/chatgpt',
